name: Build and Push to Registry
on: [push]
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy the model
        run: |
          docker compose build api
          docker tag ${{ secrets.IMAGE_NAME }} ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          echo "${{ secrets.PASSWORD }}" | docker login --username ${{ secrets.USERNAME }} --password-stdin ${{ secrets.REGISTRY }}
          docker push ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          printf "Image pushed successfully\n"

      - name: Pull on the VM
        run: |
          ssh ubuntu@${{ secrets.IP }} "docker pull ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}"
          printf "Image pulled successfully\n"