name: Build and Push to Registry
on: [push]
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy the model
        run: |
          docker compose build api
          echo "Docker compose build done"
          docker tag api ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}
          echo "Logged in"
          docker push ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          echo "Deploy the model done"

      - name: Set up SSH key  
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 ${{ secrets.ARTIFACT_HOST }} >> ~/.ssh/known_hosts
          sudo apt-get install sshpass
          
      - name: Pull on the VM
        run: |
          sshpass -p "${{ secrets.REGISTRY_PASSWORD }}" ssh ubuntu@${{ secrets.IP }} -o StrictHostKeyChecking=no \
          docker pull ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} &&\
          echo "Image pulled successfully\n"