name: Build and Push to Registry
on: [push]
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy the model
        run: |
          docker compose build api
          echo "Docker compose build done"
          docker tag api ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}
          echo "Logged in"
          docker push ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          echo "Deploy the model done"

      - name: Pull on the VM
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" ssh ubuntu@${{ secrets.IP }} -o StrictHostKeyChecking=no << EOF
          docker pull ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          printf "Image pulled successfully\n"